version: "3.8"
services:
  ds-app:
    build: .
    container_name: ds-app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
      - NVDSINFER_LOG_LEVEL=3            # Bật log DeepStream (TensorRT + nvinfer)
      - GST_DEBUG=nvinfer:4,nvstreammux:3,nvdsosd:3 # Bật log chi tiết GStreamer
      - GST_DEBUG_DUMP_DOT_DIR=/output   # Xuất sơ đồ pipeline .dot
    network_mode: host
    volumes:
      - ./models:/models
      - ./configs:/configs
      - ./app:/app
      - ./output:/output
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["python3", "/app/main.py", "--video", "/app/sample.mp4"]

